### ISSUE TITLE
Directory Rename and Structure Change

### ISSUE THREAD

**Issue by NiklasWang** [NiklasWang/Uranium#1]
external/coreutils-5_0-md5sum_sha1sum  rename to -> external/md5sum_sha1sum
external/libuuid-1_0_3 rename to -> external/libuuid
external/openssl-1_0_2r-aes -> external/aes

Add Readme to clarify, souce code is coming from which open source project

Create test to each directory, use their own test function as their tester.

Create a encrypt directory, move all we implemented source code into this, add our own tester.

**Comment by msrLi** [comment]
Solve these at 642c4c03fe592c0c0cf17101216ca31c8a08eea0
